
<div class="container">
    <div class="row">
        <div class="col text-center home-index">
            <figure>
                <img src="/assets/img/worksena-min.png" class="img-fluid logo-home">
            </figure>
            <h3><?= $version ?></h3>
<!--            <h4>Micro Framework <strong>PHP</strong></h4>-->
            <div class="link">
                <a href="https://www.worksena.xyz/documentacao" target="_blank">Documentação</a>
                <a href="https://www.worksena.xyz/sobre" target="_blank">Sobre</a>
                <a href="https://github.com/WalderlanSena/worksena/issues" target="_blank">Ajuda</a>
                <a href="https://worksena.xyz/docs/servidor" target="_blank">Exemplos</a>
            </div>
            <a href="https://worksena.xyz">https://worksena.xyz</a>
            <br>
            <br>
            <br>
            <p>© 2013 - 2018 ~ <strong>Mentes Virtuais Sena.</strong></p>
        </div>
    </div>
</div>